[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'
molokai_original = 1
rehash256 = 1
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1

  let g:airline_left_sep = '⮀'
  let g:airline_left_alt_sep = '⮁'
  let g:airline_right_sep = '⮂'
  let g:airline_right_alt_sep = '⮃'
  let g:airline_branch_prefix = '⭠'
  let g:airline_readonly_symbol = '⭤'
  let g:airline_linecolumn_prefix = '⭡'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'mattn/emmet-vim'
user_emmet_settings = '{
  "variables": {
    "lang" : "ja"
  }
}'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  source $XDG_CONFIG_HOME/nvim/plugins/coc.rc.vim
'''
